---
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - mysql-server
      - python3-pymysql
      state: latest
      update_cache: yes
    become: yes
  - name: Create a new database with name '{{ wp_db_name }}'
    community.mysql.mysql_db:
      name: '{{ wp_db_name }}'
      state: present
      login_unix_socket: '{{ unix_socket }}'
    become: yes
  - name: Create database user with name '{{ wp_db_user }}' and password '{{ wp_db_pass }}' with some database privileges
    community.mysql.mysql_user:
      name: '{{ wp_db_user }}'
      password: '{{ wp_db_pass }}'
      priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
      login_unix_socket: '{{ unix_socket }}'
      host: '{{ item }}'
    with_items:
    - 'localhost'
    - '127.0.0.1'
    # - '192.168.0.16'
    - '{{ wp_ip }}'
    become: yes
  - name: Configurar database
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '{{ item.regexp }}'
      replace: '{{ item.replace }}'
    with_items: 
    - {regexp: '127.0.0.1', replace: '0.0.0.0'}
    become: yes
    notify:
    - restart mysql